services:
  - type: web
    name: nodejs
    buildCommand: npm install && npm run build
    startCommand: node server.js
    runtime: nodejs-16

  - type: web
    name: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scan.py
    runtime: python-3.9
